
nilead.backend.navigation.index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: nilead.controller.navigation:indexAction
        _nilead:
           template: NileadWebBundle:Backend/Navigation:index.html.twig
            # method: createPaginator
            # arguments: [$criteria, $sorting]

nilead.backend.navigation.create:
    pattern: /create
    methods: [GET]
    defaults:
        _controller: nilead.controller.navigation:createAction
        _nilead:
            template: NileadWebBundle:Backend/Navigation:create.html.twig
            redirect: nilead.backend.navigation.update

nilead.backend.navigation.store:
    pattern: /create
    methods: [POST]
    defaults:
        _controller: nilead.controller.navigation:createAction
        _nilead:
            template: NileadWebBundle:Backend/Navigation:create.html.twig
            redirect: nilead.backend.navigation.update

nilead.backend.navigation.update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: nilead.controller.navigation:updateAction
        _nilead:
            template: NileadWebBundle:Backend/Navigation:update.html.twig
            redirect: nilead.backend.navigation.index

nilead.backend.navigation.delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: nilead.controller.navigation:deleteAction
        _nilead:
            redirect: nilead.backend.navigation.index

nilead.backend.navigation.filter_form:
    pattern: /filter-form
    methods: [GET]
    defaults:
        _controller: nilead.controller.navigation:filterFormAction
        _nilead:
            template: NileadWebBundle:Backend/Navigation:filterForm.html.twig

nilead.backend.navigation.show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: nilead.controller.navigation:showAction
        _nilead:
            template: NileadWebBundle:Backend/Navigation:show.html.twig
