#CATEGORY
nilead.backend.order.index:
    path: /
    defaults:
        _controller:  nilead.controller.order:indexAction
        _nilead:
            template: NileadWebBundle:Order:index.html.twig

nilead.backend.order.create:
    path: /create/
    methods: [GET, POST]
    defaults:
        _controller:  nilead.controller.order:createAction
        _nilead:
            template: NileadWebBundle:Order:create.html.twig
            redirect: nilead.backend.shipping_category.index
            
nilead.backend.order.show:
    path: /{id}
    methods: [GET, PUT]
    requirements:
        id:  \d+
    defaults:
        _controller:  nilead.controller.order:showAction
        _nilead:
            template: NileadWebBundle:Order:show.html.twig

nilead.backend.order.update:
    path: /{id}/edit/
    methods: [GET, PUT]
    requirements:
        id:  \d+
    defaults:
        _controller:  nilead.controller.order:updateAction
        _nilead:
            template: NileadWebBundle:Order:update.html.twig
            redirect: nilead.backend.shipping_category.index

nilead.backend.order.delete:
    path: /order/{id}
    methods: [DELETE]
    requirements:
        id:  \d+
    defaults:
        _controller:  nilead.controller.order:deleteAction

nilead.backend.order.change_status:
    path: /order/{id}/change_status
    methods: [POST]
    requirements:
        id:  \d+
    defaults:
        _controller:  nilead.controller.order:changeStatusAction