
nilead.backend.tax_category.index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: nilead.controller.tax_category:indexAction
        _nilead:
            template: NileadWebBundle:TaxCategory:index.html.twig
            method: createPaginator
#            arguments: [$criteria, $sorting]

nilead.backend.tax_category.create:
    pattern: /create
    methods: [GET]
    defaults:
        _controller: nilead.controller.tax_category:createAction
        _nilead:
            template: NileadWebBundle:TaxCategory:create.html.twig
            redirect: nilead.backend.tax_category.update

nilead.backend.tax_category.store:
    pattern: /create
    methods: [POST]
    defaults:
        _controller: nilead.controller.tax_category:createAction
        _nilead:
            template: NileadWebBundle:TaxCategory:create.html.twig
            redirect: nilead.backend.tax_category.update

nilead.backend.tax_category.update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: nilead.controller.tax_category:updateAction
        _nilead:
            template: NileadWebBundle:TaxCategory:update.html.twig
            redirect: nilead.backend.tax_category.update

nilead.backend.tax_category.delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: nilead.controller.tax_category:deleteAction
        _nilead:
            redirect: nilead.backend.tax_category.index

nilead.backend.tax_category.filter_form:
    pattern: /filter-form
    methods: [GET]
    defaults:
        _controller: nilead.controller.tax_category:filterFormAction
        _nilead:
            template: NileadWebBundle:TaxCategory:filterForm.html.twig

nilead.backend.tax_category.show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: nilead.controller.tax_category:showAction
        _nilead:
            template: NileadWebBundle:TaxCategory:show.html.twig
